-- Drop table

-- DROP TABLE public.persona;

CREATE TABLE public.persona (
	persona_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	direccion varchar(255) NULL,
	edad int4 NULL,
	genero varchar(255) NULL,
	identificacion varchar(255) NULL,
	nombres varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT persona_prkey PRIMARY KEY (persona_id),
	CONSTRAINT uk_r5vsms84ih2viwd6tatk9o5pr UNIQUE (identificacion)
);


-- Drop table

-- DROP TABLE public.clientes;

CREATE TABLE public.clientes (
	cliente_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	contrasenia varchar(255) NULL,
	estado bool NULL,
	persona_id int4 NOT NULL,
	CONSTRAINT clientes_prkey PRIMARY KEY (cliente_id),
	CONSTRAINT uk_nhdbltv7dnhp65s6wjb411gor UNIQUE (cliente_id),
	CONSTRAINT fkgdh25m0u6r4xr9iuqnsbbh12q FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id)
);


-- Drop table

-- DROP TABLE public.cuentas;

CREATE TABLE public.cuentas (
	cuenta_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	estado bool NULL,
	numero_cuenta varchar(255) NULL,
	saldo_inicial float8 NULL,
	tipo_cuenta varchar(255) NULL,
	cliente_id int4 NULL,
	CONSTRAINT cuentas_prkey PRIMARY KEY (cuenta_id),
	CONSTRAINT cuentas_un UNIQUE (numero_cuenta),
	CONSTRAINT fk65yk2321jpusl3fk96lqehrlj FOREIGN KEY (cliente_id) REFERENCES public.clientes(cliente_id)
);


-- Drop table

-- DROP TABLE public.movimientos;

CREATE TABLE public.movimientos(
	movimiento_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	fecha timestamp NULL,
	saldo float8 NULL,
	tipo_movimiento varchar(255) NULL,
	valor float8 NULL,
	cuenta_id int4 NULL,
	saldo_inicial float8 NULL,
	CONSTRAINT movimientos_prkey PRIMARY KEY (movimiento_id),
	CONSTRAINT fk7dg9eam32ow23n4moo6x5oo6e FOREIGN KEY (cuenta_id) REFERENCES public.cuentas(cuenta_id)
);
